import 'package:flutter/material.dart';
import 'package:track_fitness/updated_work/model/listClass.dart';

List<Listclass> WorkOutList = [
  
  Listclass(
    id: '1',
    name: 'Full Body Workout',
    color: Colors.blue,
    description: 'A comprehensive workout targeting all major muscle groups.',
    imageUrl: 'https://example.com/full_body_workout.jpg',
    createdAt: '2023-10-01',
    updatedAt: '2023-10-02',
  ),
  Listclass(
    id: '2',
    name: 'Upper Body Strength',
    description: 'Focus on building strength in the upper body.',
    color: Colors.red,
    imageUrl: 'https://example.com/upper_body_strength.jpg',
    createdAt: '2023-10-03',
    updatedAt: '2023-10-04',
  ),
  Listclass(
    id: '3',
    name: 'Lower Body Blast',
    description: 'Intensive workout for the lower body muscles.',
    color: Colors.green,
    imageUrl: 'https://example.com/lower_body_blast.jpg',
    createdAt: '2023-10-05',
    updatedAt: '2023-10-06',
  ),
  Listclass(
    id: '4',
    name: 'Core Strengthening',
    description: 'Exercises focused on strengthening the core muscles.',
    color: Colors.orange,
    imageUrl: 'https://example.com/core_strengthening.jpg',
    createdAt: '2023-10-07',
    updatedAt: '2023-10-08',
  ),
  Listclass(
    id: '5',
    name: 'Cardio Blast',
    description: 'High-intensity cardio workout to boost endurance.',
    color: Colors.purple,
    imageUrl: 'https://example.com/cardio_blast.jpg',
    createdAt: '2023-10-09',
    updatedAt: '2023-10-10',
  ),
  Listclass(
    id: '6',
    name: 'Yoga Flexibility',
    description: 'Yoga sessions to improve flexibility and relaxation.',
    color: Colors.teal,
    imageUrl: 'https://example.com/yoga_flexibility.jpg',
    createdAt: '2023-10-11',
    updatedAt: '2023-10-12',
  ),
  Listclass(
    id: '7',
    name: 'Pilates Core',
    description: 'Pilates exercises focusing on core strength and stability.',
    color: Colors.cyan,
    imageUrl: 'https://example.com/pilates_core.jpg',
    createdAt: '2023-10-13',
    updatedAt: '2023-10-14',
  ),
  Listclass(
    id: '8',
    name: 'HIIT Workout',
    description: 'High-Intensity Interval Training for maximum fat burn.',
    color: Colors.amber,
    imageUrl: 'https://example.com/hiit_workout.jpg',
    createdAt: '2023-10-15',
    updatedAt: '2023-10-16',
  ),
  Listclass(
    id: '9',
    name: 'Strength Training',
    description: 'Weight training exercises to build muscle strength.',
    color: Colors.indigo,
    imageUrl: 'https://example.com/strength_training.jpg',
    createdAt: '2023-10-17',
    updatedAt: '2023-10-18',
  ),
  Listclass(
    id: '10',
    name: 'Flexibility Routine',
    description: 'Routine focused on improving overall flexibility.',
    color: Colors.lime,
    imageUrl: 'https://example.com/flexibility_routine.jpg',
    createdAt: '2023-10-19',
    updatedAt: '2023-10-20',
  ),
  Listclass(
    id: '11',
    name: 'Balance Training',
    description: 'Exercises to enhance balance and stability.',
    color: Colors.pink,
    imageUrl: 'https://example.com/balance_training.jpg',
    createdAt: '2023-10-21',
    updatedAt: '2023-10-22',
  ),
  Listclass(
    id: '12',
    name: 'Functional Fitness',
    description: 'Workouts designed to improve everyday functional movements.',
    color: Colors.brown,
    imageUrl: 'https://example.com/functional_fitness.jpg',
    createdAt: '2023-10-23',
    updatedAt: '2023-10-24',
  ),
  Listclass(
    id: '13',
    name: 'Endurance Training',
    description: 'Training sessions focused on building endurance.',
    color: Colors.deepPurple,
    imageUrl: 'https://example.com/endurance_training.jpg',
    createdAt: '2023-10-25',
    updatedAt: '2023-10-26',
  ),
  Listclass(
    id: '14',
    name: 'Sports Conditioning',
    description: 'Conditioning workouts tailored for athletes.',
    color: Colors.deepOrange,
    imageUrl: 'https://example.com/sports_conditioning.jpg',
    createdAt: '2023-10-27',
    updatedAt: '2023-10-28',
  ),
  Listclass(
    id: '15',
    name: 'Recovery and Mobility',
    description: 'Sessions focused on recovery and improving mobility.',
    color: Colors.lightBlue,
    imageUrl: 'https://example.com/recovery_mobility.jpg',
    createdAt: '2023-10-29',
    updatedAt: '2023-10-30',
  ),
  Listclass(
    id: '16',
    name: 'Circuit Training',
    description: 'Circuit workouts combining strength and cardio exercises.',
    color: Colors.lightGreen,
    imageUrl: 'https://example.com/circuit_training.jpg',
    createdAt: '2023-10-31',
    updatedAt: '2023-11-01',
  ),
  Listclass(
    id: '17',
    name: 'Agility Training',
    description: 'Exercises to improve agility and quickness.',
    color: Colors.grey,
    imageUrl: 'https://example.com/agility_training.jpg',
    createdAt: '2023-11-02',
    updatedAt: '2023-11-03',
  ),
];